# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-02 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='wpisz Imę autorki/a', max_length=50)),
                ('last_name', models.CharField(help_text='wpisz nazwisko autorki/a', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Wpisz tytuł', max_length=100)),
                ('published', models.CharField(help_text='Wpisz datę publikacji', max_length=10)),
                ('isbn', models.CharField(help_text='wpisz SBN (13cyfr)', max_length=13, verbose_name='ISBN')),
                ('publisher', models.CharField(help_text='Wpisz wydawcę', max_length=100)),
                ('author', models.ManyToManyField(help_text='Dodaj autora/kę', to='catalog.Author')),
            ],
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Cathegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wpisz kategorię', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='wpisz język', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='wpisz Imę tłumaczki/a', max_length=50)),
                ('last_name', models.CharField(help_text='wpisz nazwisko tłumaczki/a', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='cathegory',
            field=models.ManyToManyField(help_text='wybierz kategorię', to='catalog.Cathegory'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Wybierz język', to='catalog.Language'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(help_text='Dodaj tłumaczcza/kę', to='catalog.Translator'),
        ),
    ]
