# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Autorki/rzy'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'verbose_name': 'Egzemplarz', 'verbose_name_plural': 'Egzemplarze'},
        ),
        migrations.AlterModelOptions(
            name='cathegory',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'Jęzki', 'verbose_name_plural': 'Języki'},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={'verbose_name': 'Tłmacz/ka', 'verbose_name_plural': 'Tłumaczki/e'},
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(help_text='wpisz Imę autorki/a', max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(help_text='wpisz nazwisko autorki/a', max_length=50, verbose_name='Nazwisko'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='wpisz SBN (13cyfr)', max_length=13, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(blank=True, help_text='Wybierz język', to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.CharField(help_text='Wpisz datę publikacji', max_length=10, verbose_name='Data wydania'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(help_text='Wpisz wydawcę', max_length=100, verbose_name='Wydawca'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Wpisz tytuł', max_length=100, verbose_name='Tytuł'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, help_text='Dodaj tłumaczcza/kę', to='catalog.Translator'),
        ),
        migrations.AlterField(
            model_name='cathegory',
            name='name',
            field=models.CharField(help_text='Wpisz kategorię', max_length=25, verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text='wpisz język', max_length=25, verbose_name='Język'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='first_name',
            field=models.CharField(help_text='wpisz Imę tłumaczki/a', max_length=50, verbose_name='Imię'),
        ),
        migrations.AlterField(
            model_name='translator',
            name='last_name',
            field=models.CharField(help_text='wpisz nazwisko tłumaczki/a', max_length=50, verbose_name='Nazwisko'),
        ),
    ]
