# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20170505_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'verbose_name': 'Książka', 'verbose_name_plural': 'Książki'},
        ),
        migrations.AlterField(
            model_name='book',
            name='cathegory',
            field=models.ManyToManyField(default='---', help_text='wybierz kategorię', to='catalog.Cathegory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='wpisz ISBN (13cyfr)', max_length=13, verbose_name='ISBN'),
        ),
    ]
