# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20170510_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='numer regału', max_length=40)),
            ],
            options={
                'verbose_name': 'Regał',
                'verbose_name_plural': 'Regały',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name_plural': 'Autorki_rzy'},
        ),
        migrations.AlterModelOptions(
            name='translator',
            options={'verbose_name': 'Tłmacz_ka', 'verbose_name_plural': 'Tłumaczki_e'},
        ),
        migrations.AddField(
            model_name='book',
            name='shelf',
            field=models.CharField(blank=True, help_text='półka', max_length=2, verbose_name='Półka'),
        ),
        migrations.AddField(
            model_name='book',
            name='place',
            field=models.ForeignKey(blank=True, help_text='Podaj regał', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Regal'),
        ),
    ]
