# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20170512_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cathegory',
            field=models.ManyToManyField(blank=True, default='---', help_text='wybierz kategorię', to='catalog.Cathegory'),
        ),
        migrations.AlterField(
            model_name='book',
            name='shelf',
            field=models.CharField(blank=True, help_text='półka', max_length=10, verbose_name='Półka'),
        ),
        migrations.AlterField(
            model_name='regal',
            name='name',
            field=models.CharField(help_text='numer regału', max_length=40, verbose_name='Nazwa'),
        ),
    ]
