# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20170514_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(help_text='Wpisz tytuł', max_length=200, verbose_name='Tytuł'),
        ),
    ]
