# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20170514_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, help_text='Dodaj tłumaczcza/kę', null=True, to='catalog.Translator'),
        ),
    ]
