# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-20 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20170514_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wpisz kategorię', max_length=25, verbose_name='Kategoria')),
                ('description', models.CharField(blank=True, help_text='Dodaj opis kategorii', max_length=50, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='cathegory',
        ),
        migrations.DeleteModel(
            name='Cathegory',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(blank=True, default='---', help_text='wybierz kategorię', to='catalog.Category'),
        ),
    ]
